### ISSUE TITLE
Get http://octopals.rocks working

### ISSUE THREAD

**Issue by jcatterton** [myran2/octopals.org#3]
Seriously what the heck

**Comment by myran2** [comment]
i fixed the nameserver settings, maybe it'll work now

**Comment by jcatterton** [comment]
did you open a PR???

**Comment by jcatterton** [comment]
Issue isn't fixed, we need all hands on deck, this is a critical issue
